/**
 * Extended OBD-II PID Catalog
 *
 * Mutatively registers ~60 additional Mode 01 PIDs into the PIDS object
 * from obd-pids.js. This is idempotent — re-importing this module is safe.
 * The existing decodePID() function works for all PIDs with zero changes.
 */

import { PIDS } from './obd-pids.js';

// --- Category definitions ---
export const PID_CATEGORIES = {
  engine: { label: 'Engine', icon: '🔧' },
  speed_load: { label: 'Speed & Load', icon: '🏎' },
  fuel: { label: 'Fuel System', icon: '⛽' },
  o2: { label: 'O2 Sensors', icon: '💨' },
  emissions: { label: 'Emissions', icon: '🌿' },
  electrical: { label: 'Electrical', icon: '🔋' },
  exhaust: { label: 'Exhaust & Catalyst', icon: '🌡' },
};

// Tag each existing PID with a category
const EXISTING_CATEGORIES = {
  '0C': 'engine',      // RPM
  '0D': 'speed_load',  // Speed
  '05': 'engine',      // Coolant
  '0B': 'engine',      // Boost / Intake Manifold
  '04': 'speed_load',  // Load
  '11': 'speed_load',  // Throttle
  '0F': 'engine',      // IAT
  '06': 'fuel',        // STFT B1
  '07': 'fuel',        // LTFT B1
  '10': 'fuel',        // MAF
};

// Apply categories to existing PIDs
for (const [pid, cat] of Object.entries(EXISTING_CATEGORIES)) {
  if (PIDS[pid]) PIDS[pid].category = cat;
}

// --- Extended PIDs ---
const EXTENDED = {
  // ===== Engine =====
  '03': {
    name: 'Fuel Status',
    description: 'Fuel System Status',
    unit: '',
    bytes: 2,
    min: 0,
    max: 16,
    warnAbove: null,
    formula: (A) => A,
    category: 'engine',
  },
  '0A': {
    name: 'Fuel Press',
    description: 'Fuel Pressure (Gauge)',
    unit: 'kPa',
    bytes: 1,
    min: 0,
    max: 765,
    warnAbove: null,
    formula: (A) => A * 3,
    category: 'engine',
  },
  '0E': {
    name: 'Timing Adv',
    description: 'Timing Advance',
    unit: '°',
    bytes: 1,
    min: -64,
    max: 63.5,
    warnAbove: null,
    formula: (A) => (A / 2) - 64,
    category: 'engine',
  },
  '1C': {
    name: 'OBD Std',
    description: 'OBD Standards Compliance',
    unit: '',
    bytes: 1,
    min: 0,
    max: 255,
    warnAbove: null,
    formula: (A) => A,
    category: 'engine',
  },
  '1F': {
    name: 'Run Time',
    description: 'Run Time Since Engine Start',
    unit: 's',
    bytes: 2,
    min: 0,
    max: 65535,
    warnAbove: null,
    formula: (A, B) => (A * 256) + B,
    category: 'engine',
  },
  '2F': {
    name: 'Fuel Level',
    description: 'Fuel Tank Level Input',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'engine',
  },
  '30': {
    name: 'Warm-ups',
    description: 'Warm-ups Since Codes Cleared',
    unit: '',
    bytes: 1,
    min: 0,
    max: 255,
    warnAbove: null,
    formula: (A) => A,
    category: 'engine',
  },
  '31': {
    name: 'Dist CLR',
    description: 'Distance Since Codes Cleared',
    unit: 'km',
    bytes: 2,
    min: 0,
    max: 65535,
    warnAbove: null,
    formula: (A, B) => (A * 256) + B,
    category: 'engine',
  },
  '33': {
    name: 'Baro Press',
    description: 'Barometric Pressure',
    unit: 'kPa',
    bytes: 1,
    min: 0,
    max: 255,
    warnAbove: null,
    formula: (A) => A,
    category: 'engine',
  },
  '46': {
    name: 'Ambient',
    description: 'Ambient Air Temperature',
    unit: '°C',
    bytes: 1,
    min: -40,
    max: 215,
    warnAbove: null,
    formula: (A) => A - 40,
    category: 'engine',
  },
  '5C': {
    name: 'Oil Temp',
    description: 'Engine Oil Temperature',
    unit: '°C',
    bytes: 1,
    min: -40,
    max: 210,
    warnAbove: 130,
    formula: (A) => A - 40,
    category: 'engine',
  },

  // ===== Speed & Load =====
  '21': {
    name: 'Dist MIL',
    description: 'Distance with MIL On',
    unit: 'km',
    bytes: 2,
    min: 0,
    max: 65535,
    warnAbove: null,
    formula: (A, B) => (A * 256) + B,
    category: 'speed_load',
  },
  '43': {
    name: 'Abs Load',
    description: 'Absolute Load Value',
    unit: '%',
    bytes: 2,
    min: 0,
    max: 25700,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) / 2.55,
    category: 'speed_load',
  },
  '45': {
    name: 'Rel Throttle',
    description: 'Relative Throttle Position',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'speed_load',
  },
  '47': {
    name: 'Abs TP B',
    description: 'Absolute Throttle Position B',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'speed_load',
  },
  '48': {
    name: 'Abs TP C',
    description: 'Absolute Throttle Position C',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'speed_load',
  },
  '49': {
    name: 'Accel D',
    description: 'Accelerator Pedal Position D',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'speed_load',
  },
  '4A': {
    name: 'Accel E',
    description: 'Accelerator Pedal Position E',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'speed_load',
  },
  '4B': {
    name: 'Accel F',
    description: 'Accelerator Pedal Position F',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'speed_load',
  },
  '4C': {
    name: 'Cmd Throt',
    description: 'Commanded Throttle Actuator',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'speed_load',
  },
  '4D': {
    name: 'MIL Time',
    description: 'Time Run with MIL On',
    unit: 'min',
    bytes: 2,
    min: 0,
    max: 65535,
    warnAbove: null,
    formula: (A, B) => (A * 256) + B,
    category: 'speed_load',
  },
  '4E': {
    name: 'CLR Time',
    description: 'Time Since Codes Cleared',
    unit: 'min',
    bytes: 2,
    min: 0,
    max: 65535,
    warnAbove: null,
    formula: (A, B) => (A * 256) + B,
    category: 'speed_load',
  },

  // ===== Fuel System =====
  '08': {
    name: 'STFT B2',
    description: 'Short Term Fuel Trim — Bank 2',
    unit: '%',
    bytes: 1,
    min: -100,
    max: 99.2,
    warnAbove: 25,
    formula: (A) => ((A / 128) - 1) * 100,
    category: 'fuel',
  },
  '09': {
    name: 'LTFT B2',
    description: 'Long Term Fuel Trim — Bank 2',
    unit: '%',
    bytes: 1,
    min: -100,
    max: 99.2,
    warnAbove: 25,
    formula: (A) => ((A / 128) - 1) * 100,
    category: 'fuel',
  },
  '22': {
    name: 'Rail Press',
    description: 'Fuel Rail Pressure (Relative)',
    unit: 'kPa',
    bytes: 2,
    min: 0,
    max: 5177.265,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) * 0.079,
    category: 'fuel',
  },
  '23': {
    name: 'Rail Gauge',
    description: 'Fuel Rail Gauge Pressure (Diesel)',
    unit: 'kPa',
    bytes: 2,
    min: 0,
    max: 655350,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) * 10,
    category: 'fuel',
  },
  '2C': {
    name: 'Cmd EGR',
    description: 'Commanded EGR',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'fuel',
  },
  '2D': {
    name: 'EGR Err',
    description: 'EGR Error',
    unit: '%',
    bytes: 1,
    min: -100,
    max: 99.2,
    warnAbove: null,
    formula: (A) => ((A / 128) - 1) * 100,
    category: 'fuel',
  },
  '2E': {
    name: 'Cmd Evap',
    description: 'Commanded Evaporative Purge',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'fuel',
  },
  '44': {
    name: 'Cmd AFR',
    description: 'Commanded Air-Fuel Ratio',
    unit: '',
    bytes: 2,
    min: 0,
    max: 2,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) / 32768,
    category: 'fuel',
  },
  '51': {
    name: 'Fuel Type',
    description: 'Fuel Type',
    unit: '',
    bytes: 1,
    min: 0,
    max: 23,
    warnAbove: null,
    formula: (A) => A,
    category: 'fuel',
  },
  '52': {
    name: 'Ethanol %',
    description: 'Ethanol Fuel Percentage',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'fuel',
  },
  '59': {
    name: 'Rail Abs',
    description: 'Fuel Rail Absolute Pressure',
    unit: 'kPa',
    bytes: 2,
    min: 0,
    max: 655350,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) * 10,
    category: 'fuel',
  },
  '5A': {
    name: 'Rel Accel',
    description: 'Relative Accelerator Pedal Position',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'fuel',
  },
  '5E': {
    name: 'Fuel Rate',
    description: 'Engine Fuel Rate',
    unit: 'L/h',
    bytes: 2,
    min: 0,
    max: 3276.75,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) / 20,
    category: 'fuel',
  },

  // ===== O2 Sensors =====
  '14': {
    name: 'O2 B1S1 V',
    description: 'O2 Sensor Voltage — Bank 1, Sensor 1',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 1.275,
    warnAbove: null,
    formula: (A) => A / 200,
    category: 'o2',
  },
  '15': {
    name: 'O2 B1S2 V',
    description: 'O2 Sensor Voltage — Bank 1, Sensor 2',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 1.275,
    warnAbove: null,
    formula: (A) => A / 200,
    category: 'o2',
  },
  '16': {
    name: 'O2 B1S3 V',
    description: 'O2 Sensor Voltage — Bank 1, Sensor 3',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 1.275,
    warnAbove: null,
    formula: (A) => A / 200,
    category: 'o2',
  },
  '17': {
    name: 'O2 B1S4 V',
    description: 'O2 Sensor Voltage — Bank 1, Sensor 4',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 1.275,
    warnAbove: null,
    formula: (A) => A / 200,
    category: 'o2',
  },
  '18': {
    name: 'O2 B2S1 V',
    description: 'O2 Sensor Voltage — Bank 2, Sensor 1',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 1.275,
    warnAbove: null,
    formula: (A) => A / 200,
    category: 'o2',
  },
  '19': {
    name: 'O2 B2S2 V',
    description: 'O2 Sensor Voltage — Bank 2, Sensor 2',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 1.275,
    warnAbove: null,
    formula: (A) => A / 200,
    category: 'o2',
  },
  '1A': {
    name: 'O2 B2S3 V',
    description: 'O2 Sensor Voltage — Bank 2, Sensor 3',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 1.275,
    warnAbove: null,
    formula: (A) => A / 200,
    category: 'o2',
  },
  '1B': {
    name: 'O2 B2S4 V',
    description: 'O2 Sensor Voltage — Bank 2, Sensor 4',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 1.275,
    warnAbove: null,
    formula: (A) => A / 200,
    category: 'o2',
  },
  '24': {
    name: 'O2 WR B1S1',
    description: 'O2 Sensor (Wideband) — Bank 1, Sensor 1',
    unit: 'ratio',
    bytes: 4,
    min: 0,
    max: 2,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) / 32768,
    category: 'o2',
  },
  '25': {
    name: 'O2 WR B1S2',
    description: 'O2 Sensor (Wideband) — Bank 1, Sensor 2',
    unit: 'ratio',
    bytes: 4,
    min: 0,
    max: 2,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) / 32768,
    category: 'o2',
  },
  '34': {
    name: 'O2 WR B1S1 I',
    description: 'O2 Sensor Current — Bank 1, Sensor 1',
    unit: 'mA',
    bytes: 4,
    min: -128,
    max: 128,
    warnAbove: null,
    formula: (A, B, C, D) => ((C * 256) + D) / 256 - 128,
    category: 'o2',
  },
  '35': {
    name: 'O2 WR B1S2 I',
    description: 'O2 Sensor Current — Bank 1, Sensor 2',
    unit: 'mA',
    bytes: 4,
    min: -128,
    max: 128,
    warnAbove: null,
    formula: (A, B, C, D) => ((C * 256) + D) / 256 - 128,
    category: 'o2',
  },

  // ===== Emissions =====
  '01': {
    name: 'Monitor',
    description: 'Monitor Status Since Clear',
    unit: '',
    bytes: 4,
    min: 0,
    max: 255,
    warnAbove: null,
    formula: (A) => A,
    category: 'emissions',
  },
  '13': {
    name: 'O2 Present',
    description: 'O2 Sensors Present (2 banks)',
    unit: '',
    bytes: 1,
    min: 0,
    max: 255,
    warnAbove: null,
    formula: (A) => A,
    category: 'emissions',
  },
  '1D': {
    name: 'O2 Loc',
    description: 'O2 Sensor Locations',
    unit: '',
    bytes: 1,
    min: 0,
    max: 255,
    warnAbove: null,
    formula: (A) => A,
    category: 'emissions',
  },
  '1E': {
    name: 'Aux In',
    description: 'Auxiliary Input Status',
    unit: '',
    bytes: 1,
    min: 0,
    max: 1,
    warnAbove: null,
    formula: (A) => A & 0x01,
    category: 'emissions',
  },

  // ===== Electrical =====
  '42': {
    name: 'Ctrl Volts',
    description: 'Control Module Voltage',
    unit: 'V',
    bytes: 2,
    min: 0,
    max: 65.535,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) / 1000,
    category: 'electrical',
  },
  '5B': {
    name: 'Hybrid Bat',
    description: 'Hybrid Battery Pack Remaining',
    unit: '%',
    bytes: 1,
    min: 0,
    max: 100,
    warnAbove: null,
    formula: (A) => (A / 255) * 100,
    category: 'electrical',
  },

  // ===== Exhaust & Catalyst =====
  '3C': {
    name: 'Cat B1S1',
    description: 'Catalyst Temperature — Bank 1, Sensor 1',
    unit: '°C',
    bytes: 2,
    min: -40,
    max: 6513.5,
    warnAbove: 800,
    formula: (A, B) => ((A * 256) + B) / 10 - 40,
    category: 'exhaust',
  },
  '3D': {
    name: 'Cat B2S1',
    description: 'Catalyst Temperature — Bank 2, Sensor 1',
    unit: '°C',
    bytes: 2,
    min: -40,
    max: 6513.5,
    warnAbove: 800,
    formula: (A, B) => ((A * 256) + B) / 10 - 40,
    category: 'exhaust',
  },
  '3E': {
    name: 'Cat B1S2',
    description: 'Catalyst Temperature — Bank 1, Sensor 2',
    unit: '°C',
    bytes: 2,
    min: -40,
    max: 6513.5,
    warnAbove: 800,
    formula: (A, B) => ((A * 256) + B) / 10 - 40,
    category: 'exhaust',
  },
  '3F': {
    name: 'Cat B2S2',
    description: 'Catalyst Temperature — Bank 2, Sensor 2',
    unit: '°C',
    bytes: 2,
    min: -40,
    max: 6513.5,
    warnAbove: 800,
    formula: (A, B) => ((A * 256) + B) / 10 - 40,
    category: 'exhaust',
  },
  '53': {
    name: 'Evap VP',
    description: 'Absolute Evap System Vapour Pressure',
    unit: 'kPa',
    bytes: 2,
    min: 0,
    max: 327.675,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) / 200,
    category: 'exhaust',
  },
  '54': {
    name: 'Evap VP2',
    description: 'Evap System Vapour Pressure',
    unit: 'Pa',
    bytes: 2,
    min: -32767,
    max: 32767,
    warnAbove: null,
    formula: (A, B) => ((A * 256) + B) - 32767,
    category: 'exhaust',
  },
};

// Mutatively register extended PIDs into the shared PIDS object
Object.assign(PIDS, EXTENDED);

/**
 * Get all PIDs grouped by category.
 * Returns { [categoryKey]: { label, icon, pids: [{ pid, ...def }] } }
 */
export function getPIDsByCategory() {
  const grouped = {};
  for (const [key, meta] of Object.entries(PID_CATEGORIES)) {
    grouped[key] = { ...meta, pids: [] };
  }
  for (const [pid, def] of Object.entries(PIDS)) {
    const cat = def.category || 'engine';
    if (!grouped[cat]) continue;
    grouped[cat].pids.push({ pid, ...def });
  }
  // Sort PIDs within each category by hex code
  for (const cat of Object.values(grouped)) {
    cat.pids.sort((a, b) => parseInt(a.pid, 16) - parseInt(b.pid, 16));
  }
  return grouped;
}

/**
 * Get all catalog PID codes (original + extended).
 */
export function getAllCatalogPIDs() {
  return Object.keys(PIDS);
}
